sonar.projectKey=EasyPrint_Final_Submission
sonar.projectName=EasyPrint Project

sonar.sources=backend,my-app

sonar.sourceEncoding=UTF-8
sonar.language=js

sonar.javascript.lcov.reportPaths=my-app/coverage/lcov.info,backend/coverage/lcov.info

sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**