
sonar.projectKey=EasyPrint 
sonar.organization=03panyaporn
sonar.projectName=EasyPrint Project
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**, **/.next/**, **/dist/**, **/results/**, **/tests/**, package-lock.json

sonar.language=js